name = modular_computers
title = Modular Computers
description = Adds various computers and peripherals to Minetest, similar to OpenComputers
supported_games = minetest_game, mineclonia, mineclone2
author = impulse
optional_depends = default, mesecons, mesecons_wires, mesecons_torch, mesecons_luacontroller, mesecons_delayer, basic_materials, mcl_core, mcl_copper, mcl_sounds, mcl_panes, mcl_redstone, mcl_redstone_torch, mcl_repeaters, xpanes
