name: Linting

on:
  push:
    branches: [main]
    paths:
      - '**.lua'
  pull_request:
    branches: [main]
    paths:
      - '**.lua'

jobs:
  luacheck:
    name: Lint tbe code using luacheck
    runs-on: ubuntu-latest

    container:
      image: pipelinecomponents/luacheck:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run LuaCheck
        run: luacheck .
